import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartContextProvider } from "@/context/cart";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} antialiased`}>
        <main className="pb-8">
          <CartContextProvider>{children}</CartContextProvider>
        </main>
      </body>
    </html>
  );
}
